Updated the deployment.yml and added ingress.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -32,7 +32,12 @@ deploy:
     entrypoint: [""]
   script:
     - kubectl cluster-info
-    - sed -i "s|\${IMAGE_TAG}|$CI_COMMIT_SHORT_SHA|g" K8s/deployment.yml
-    - kubectl apply -f K8s/deployment.yml
-    - kubectl rollout status deployment java-deployment -n java-app --timeout=120s
+    - sed -i "s|\${IMAGE_TAG}|$CI_COMMIT_SHORT_SHA|g" K8s/*.yml
+    - kubectl apply -f K8s/
+    - |
+      if ! kubectl rollout status deployment java-deployment -n java-app --timeout=120s; then
+        echo "---- Rollout failed, rolling back ---- "
+        kubectl rollout undo deployment java-deployment -n java-app
+        exit 1
+      fi
   when: manual
